baseurl = ""
relativeurls = true
languageCode = "en-us"
title = "IPFS Distributions"

[params]
[params.targetMap]
386 = "32-bit"
amd64 = "64-bit"
arm = "ARM"

[params.architectureMap]
"darwin Binary" = "Mac OS X Binary"
"freebsd Binary" = "FreeBSD Binary"
"linux Binary" = "Linux Binary"
"windows Binary" = "Windows Binary"
